### ISSUE TITLE
Y movement same color as Comment?

### ISSUE THREAD

**Issue by fredklanIII** [Milys/NC-Gcode-VSCode#6] opened 2019-12-21 16:35 UTC
Thanks for making the Extension,

Is there a way I can manually change the colors from your file?

**Comment by CollinKorver** [comment] 2020-03-24 15:43
Bump

**Comment by scottmwyant** [comment] 2020-04-02 01:03
Short answer:  Yes. Watch this video and post back here if you need help. 

https://youtu.be/Su-cNLe0dgw


Long answer:

This extension provides the “grammar” for the language. This is what tells VS code how to chop a document up into little parts for formatting (colorization, etc).

The formatting for each little piece is determined by the theme. Change your theme and the colorization changes.

I use the default vs code dark theme which also happens to be the theme used to present the extension to the marketplace.  One of the things I like about this extension is that the X is red, Y is green, and Z is blue.  I’ll assume that was done intentionally; it’s what we’re used to seeing in CAD/CAM systems.

I’ll look into this a little more.  We may be able to change the color of the comments.  The sure fire way to do this would be to have the extension provide a theme in addition to the grammar. But then we’d be forcing users to use our theme.

The root of the problem is that CNC folks (like me) want the red, green, blue colorization. The fact that certain elements are easily associated with a standard color scheme is unique  to this language and apparently not something VS code team has come across.

**Comment by scottmwyant** [comment] 2020-06-13 02:01
Fixed in 88b6e768f4850e1ea05b29a9fcaa03e72e936d46.  New extension released as [ML2.nc-gcode](https://marketplace.visualstudio.com/items?itemName=ML2.nc-gcode). Please see readme.md

**Closed as completed by scottmwyant** 2020-06-13 02:01 UTC
